### ISSUE TITLE
Errors at measure table 

### ISSUE THREAD

**Issue by ErwinBerkouwer1** [andreasjongenburger/power-bi-sidekick#1]
Hi Andreas,

I get timeout errors for measure tables (more than 500 measures) when i try to load the sidekick dashboard. Does the amount of measures affect the dashboard? Or do i have to look into other directions for this issue?

Reg,
Erwin

**Comment by andreasjongenburger** [comment]
Hi Erwin,

thanks for reaching out! The number of measures and especially the number and depth of measures referencing each other have an impact on load time.  

I just tested the model with 506 and 997 measures with reference level depth of max 5. The first run took about 3,5 minutes, the second a minute longer, 4,5 minutes. So I guess that should not be a problem...

I also see that RAM consumes approx. 7GB while running. Might that be a problem?
Did you try it on one local file (scenario 1)?

Best,
Andreas

**Comment by ErwinBerkouwer1** [comment]
Hi Andreas,

Thanks for your reply. Managed the issue. The reports had some issues with different data sources. Finally, the tool is working perfectly. Thanks for your help!

**Comment by andreasjongenburger** [comment]
Great, Erwin! Then I will close this.
