### ISSUE TITLE
Errors on GetReportFilters break refresh

### ISSUE THREAD

**Issue by Remko1981** [andreasjongenburger/power-bi-sidekick#3]
While using a live connection to SSAS we encountered a situation where reportfilters where broken after a field was renamed. The refresh failed when this happened. After repairing the broken filter it worked again.

![afbeelding](https://github.com/andreasjongenburger/power-bi-sidekick/assets/24568503/f8ecdb96-8980-47db-b47c-1f66250cb577)

**Comment by andreasjongenburger** [comment]
Thanks for your input Remko, 

It is not clear exactly what caused the fail based on the example provided.
Can you please share a report that contains this error? A pbit-file (without any privacy-related content) would be fine.

Best,
Andreas

**Comment by Remko1981** [comment]
Sorry for my late reply Andreas, i did not get a notification that you asked a question.

I can make an example for you. Though i only can reproduce the problem when using a live connection to an on prem SSAS server. Is a PBIT enough then?

**Comment by andreasjongenburger** [comment]
Hi @Remko1981, 
Sorry,  been really busy and missed your post here. 
Please PM me on LinkedIn to be certain I don't miss out. :-)

You are right, I need real data to see what's going on. Maybe with a sample in the form of an csv-export containing the error?
